#include "FEC.h"
#include <cmath>
#include <limits>
#include <algorithm>
#include <set>
#include <cassert>
#include <cstring>

namespace HavenFSK {

// ── Embedded LDPC(192,96) parity check matrix ─────────────────────────────
// Generated by Progressive Edge Growth, seed=1234, d_v=3, d_c=6
// DO NOT MODIFY — must match Python reference for interoperability
// Each row contains the 6 column indices where H[row][col] = 1
static const int H_NONZERO[96][6] = {
    {8, 46, 88, 106, 132, 190},
    {26, 32, 81, 99, 153, 174},
    {30, 54, 67, 96, 131, 184},
    {9, 37, 84, 112, 147, 167},
    {8, 33, 69, 109, 147, 171},
    {24, 38, 74, 102, 149, 188},
    {21, 41, 73, 101, 148, 179},
    {28, 50, 81, 122, 133, 161},
    {15, 62, 81, 127, 151, 163},
    {27, 63, 75, 116, 135, 172},
    {11, 36, 80, 100, 144, 189},
    {8, 43, 72, 119, 145, 176},
    {18, 61, 85, 111, 148, 182},
    {21, 62, 92, 114, 147, 175},
    {18, 58, 76, 106, 141, 191},
    {2, 32, 70, 117, 134, 190},
    {20, 51, 68, 123, 138, 191},
    {9, 33, 79, 129, 142, 167},
    {24, 44, 87, 125, 137, 162},
    {14, 56, 64, 100, 134, 173},
    {10, 37, 73, 100, 159, 188},
    {13, 62, 65, 97, 133, 185},
    {29, 60, 94, 118, 146, 185},
    {28, 34, 93, 102, 144, 187},
    {1, 38, 94, 104, 135, 176},
    {2, 52, 66, 115, 141, 184},
    {9, 54, 76, 124, 150, 174},
    {30, 42, 91, 105, 146, 166},
    {13, 35, 66, 104, 143, 177},
    {3, 58, 93, 112, 137, 162},
    {4, 44, 84, 120, 134, 182},
    {25, 37, 83, 110, 139, 165},
    {31, 42, 68, 107, 150, 175},
    {17, 34, 76, 114, 157, 181},
    {3, 45, 77, 103, 136, 167},
    {4, 33, 89, 97, 130, 164},
    {24, 58, 65, 103, 136, 165},
    {30, 55, 82, 129, 145, 179},
    {0, 44, 72, 118, 143, 179},
    {26, 43, 68, 123, 124, 189},
    {13, 50, 77, 111, 133, 172},
    {17, 32, 80, 108, 116, 175},
    {7, 53, 88, 126, 159, 180},
    {21, 57, 83, 121, 140, 181},
    {19, 40, 75, 107, 151, 176},
    {6, 45, 64, 96, 141, 178},
    {12, 45, 66, 117, 150, 188},
    {0, 51, 86, 99, 140, 187},
    {19, 49, 72, 111, 142, 161},
    {7, 41, 75, 120, 132, 173},
    {3, 60, 79, 110, 139, 183},
    {29, 47, 95, 113, 131, 165},
    {16, 40, 91, 122, 159, 186},
    {2, 59, 91, 119, 152, 177},
    {22, 42, 90, 121, 129, 190},
    {1, 36, 83, 125, 131, 164},
    {18, 48, 80, 106, 156, 184},
    {23, 54, 87, 101, 157, 170},
    {20, 55, 95, 124, 148, 166},
    {5, 46, 70, 121, 136, 172},
    {14, 61, 70, 126, 157, 163},
    {23, 56, 86, 109, 130, 170},
    {15, 63, 85, 96, 155, 183},
    {6, 41, 64, 99, 128, 168},
    {16, 39, 65, 128, 154, 182},
    {25, 36, 92, 105, 151, 162},
    {19, 57, 78, 109, 137, 164},
    {11, 50, 79, 115, 143, 191},
    {27, 53, 67, 122, 152, 170},
    {12, 53, 89, 123, 158, 169},
    {4, 63, 74, 113, 127, 160},
    {29, 46, 69, 128, 138, 177},
    {22, 52, 94, 118, 154, 163},
    {16, 35, 78, 108, 152, 169},
    {12, 40, 69, 105, 132, 171},
    {27, 61, 92, 110, 125, 160},
    {10, 35, 67, 102, 140, 169},
    {22, 38, 71, 120, 155, 183},
    {26, 57, 82, 113, 153, 186},
    {1, 34, 89, 98, 142, 186},
    {23, 49, 71, 119, 139, 181},
    {31, 60, 93, 126, 149, 166},
    {25, 51, 90, 98, 154, 180},
    {5, 48, 87, 108, 138, 187},
    {0, 59, 95, 98, 135, 180},
    {28, 56, 74, 115, 144, 178},
    {31, 39, 73, 127, 146, 185},
    {17, 47, 90, 116, 155, 189},
    {7, 39, 86, 103, 145, 161},
    {5, 49, 88, 107, 130, 173},
    {20, 48, 84, 114, 153, 160},
    {14, 43, 82, 104, 156, 171},
    {11, 55, 71, 97, 158, 168},
    {15, 52, 78, 101, 156, 178},
    {10, 47, 85, 117, 149, 174},
    {6, 59, 77, 112, 158, 168},
};

// ── Constructor and matrix setup ──────────────────────────────────────────

FEC::FEC() {
    buildMatrixFromEmbedded();
    buildSparseGraph();
    buildEncoder();
}

void FEC::buildMatrixFromEmbedded() {
    m_H.assign(LDPC_M, std::vector<uint8_t>(LDPC_N, 0));
    for (int i = 0; i < LDPC_M; i++)
        for (int k = 0; k < 6; k++)
            m_H[i][H_NONZERO[i][k]] = 1;
}

void FEC::buildSparseGraph() {
    m_varToCheck.assign(LDPC_N, {});
    m_checkToVar.assign(LDPC_M, {});
    for (int i = 0; i < LDPC_M; i++) {
        for (int j = 0; j < LDPC_N; j++) {
            if (m_H[i][j] == 1) {
                m_varToCheck[j].push_back(i);
                m_checkToVar[i].push_back(j);
            }
        }
    }
}

// ── Encoder ───────────────────────────────────────────────────────────────

void FEC::buildEncoder() {
    // Gaussian elimination over GF(2) on H to find systematic form
    std::vector<std::vector<int>> Hw(LDPC_M, std::vector<int>(LDPC_N));
    for (int i = 0; i < LDPC_M; i++)
        for (int j = 0; j < LDPC_N; j++)
            Hw[i][j] = m_H[i][j];

    std::vector<int> pivotCols;
    int row = 0;
    for (int col = 0; col < LDPC_N && row < LDPC_M; col++) {
        int found = -1;
        for (int r = row; r < LDPC_M; r++)
            if (Hw[r][col] == 1) { found = r; break; }
        if (found == -1) continue;
        std::swap(Hw[row], Hw[found]);
        for (int r = 0; r < LDPC_M; r++) {
            if (r != row && Hw[r][col] == 1)
                for (int c = 0; c < LDPC_N; c++)
                    Hw[r][c] = (Hw[r][c] + Hw[row][c]) % 2;
        }
        pivotCols.push_back(col);
        row++;
    }

    std::set<int> pivotSet(pivotCols.begin(), pivotCols.end());
    std::vector<int> freeCols;
    for (int c = 0; c < LDPC_N; c++)
        if (pivotSet.find(c) == pivotSet.end())
            freeCols.push_back(c);

    m_colPerm.clear();
    m_colPerm.insert(m_colPerm.end(), freeCols.begin(), freeCols.end());
    m_colPerm.insert(m_colPerm.end(), pivotCols.begin(), pivotCols.end());

    m_colPermInv.resize(LDPC_N);
    for (int i = 0; i < LDPC_N; i++)
        m_colPermInv[m_colPerm[i]] = i;

    int kSys = static_cast<int>(freeCols.size());
    m_encRows.assign(LDPC_M, std::vector<uint8_t>(kSys));
    for (int i = 0; i < LDPC_M; i++)
        for (int j = 0; j < kSys; j++)
            m_encRows[i][j] = static_cast<uint8_t>(Hw[i][freeCols[j]]);
}

std::vector<uint8_t> FEC::unpackBits(const std::vector<uint8_t>& bytes) {
    std::vector<uint8_t> bits(bytes.size() * 8);
    for (int i = 0; i < (int)bytes.size(); i++)
        for (int b = 0; b < 8; b++)
            bits[i * 8 + b] = (bytes[i] >> (7 - b)) & 1;
    return bits;
}

std::vector<uint8_t> FEC::packBits(const std::vector<uint8_t>& bits) {
    std::vector<uint8_t> bytes(bits.size() / 8);
    for (int i = 0; i < (int)bytes.size(); i++) {
        uint8_t b = 0;
        for (int k = 0; k < 8; k++)
            b = (b << 1) | (bits[i * 8 + k] & 1);
        bytes[i] = b;
    }
    return bytes;
}

std::vector<float> FEC::encodeBlock(const std::vector<uint8_t>& bytes) const {
    assert((int)bytes.size() == LDPC_BYTES_PER_BLOCK);

    auto msgBits = unpackBits(bytes);  // 96 bits

    // Compute parity: parity[i] = dot(encRows[i], msgBits) mod 2
    std::vector<uint8_t> parity(LDPC_M, 0);
    for (int i = 0; i < LDPC_M; i++)
        for (int j = 0; j < LDPC_K; j++)
            parity[i] ^= m_encRows[i][j] & msgBits[j];

    // Build permuted codeword: [msgBits | parity]
    std::vector<uint8_t> cwPerm(LDPC_N);
    for (int i = 0; i < LDPC_K; i++) cwPerm[i] = msgBits[i];
    for (int i = 0; i < LDPC_M; i++) cwPerm[LDPC_K + i] = parity[i];

    // Unpermute: cw[colPerm[i]] = cwPerm[i]
    std::vector<uint8_t> cw(LDPC_N);
    for (int i = 0; i < LDPC_N; i++)
        cw[m_colPerm[i]] = cwPerm[i];

    // BPSK map: 0 -> +1.0f, 1 -> -1.0f
    std::vector<float> bpsk(LDPC_N);
    for (int i = 0; i < LDPC_N; i++)
        bpsk[i] = (cw[i] == 0) ? 1.0f : -1.0f;

    return bpsk;
}

FEC::EncodeResult FEC::encodeMessage(const std::vector<uint8_t>& payload) const {
    int origLen = static_cast<int>(payload.size());
    int nBlocks = (origLen + LDPC_BYTES_PER_BLOCK - 1) / LDPC_BYTES_PER_BLOCK;
    if (nBlocks == 0) nBlocks = 1;

    std::vector<float> allBpsk;
    allBpsk.reserve(nBlocks * LDPC_N);

    for (int b = 0; b < nBlocks; b++) {
        std::vector<uint8_t> chunk(LDPC_BYTES_PER_BLOCK, 0);
        int start = b * LDPC_BYTES_PER_BLOCK;
        int end = std::min(start + LDPC_BYTES_PER_BLOCK, origLen);
        for (int i = start; i < end; i++)
            chunk[i - start] = payload[i];
        auto blockBpsk = encodeBlock(chunk);
        allBpsk.insert(allBpsk.end(), blockBpsk.begin(), blockBpsk.end());
    }

    return EncodeResult{allBpsk, nBlocks, origLen};
}

// ── Decoder (normalized min-sum belief propagation) ───────────────────────

DecodeResult FEC::decodeBlock(const std::vector<float>& llr) const {
    assert((int)llr.size() == LDPC_N);

    // Check-to-variable messages [check_i][position in checkToVar[i]]
    std::vector<std::vector<float>> c2v(LDPC_M);
    for (int i = 0; i < LDPC_M; i++)
        c2v[i].assign(m_checkToVar[i].size(), 0.0f);

    // posInCheck[j][k] = position of variable j in checkToVar[varToCheck[j][k]]
    std::vector<std::vector<int>> posInCheck(LDPC_N);
    for (int j = 0; j < LDPC_N; j++) {
        posInCheck[j].resize(m_varToCheck[j].size());
        for (int k = 0; k < (int)m_varToCheck[j].size(); k++) {
            int chk = m_varToCheck[j][k];
            for (int p = 0; p < (int)m_checkToVar[chk].size(); p++) {
                if (m_checkToVar[chk][p] == j) {
                    posInCheck[j][k] = p;
                    break;
                }
            }
        }
    }

    bool converged = false;
    int iter = 0;

    for (iter = 0; iter < LDPC_MAX_ITERATIONS; iter++) {

        // ── Variable to check messages ────────────────────────────────────
        std::vector<std::vector<float>> v2c(LDPC_M);
        for (int i = 0; i < LDPC_M; i++)
            v2c[i].assign(m_checkToVar[i].size(), 0.0f);

        for (int j = 0; j < LDPC_N; j++) {
            float totalC2V = 0.0f;
            for (int k = 0; k < (int)m_varToCheck[j].size(); k++)
                totalC2V += c2v[m_varToCheck[j][k]][posInCheck[j][k]];

            for (int k = 0; k < (int)m_varToCheck[j].size(); k++) {
                int chk = m_varToCheck[j][k];
                int pos = posInCheck[j][k];
                v2c[chk][pos] = llr[j] + totalC2V - c2v[chk][pos];
            }
        }

        // ── Check to variable messages (normalized min-sum) ───────────────
        for (int i = 0; i < LDPC_M; i++) {
            int deg = static_cast<int>(m_checkToVar[i].size());

            float minAbs1 = std::numeric_limits<float>::max();
            float minAbs2 = std::numeric_limits<float>::max();
            int minIdx = 0;
            int signProd = 0;

            for (int pos = 0; pos < deg; pos++) {
                float v = v2c[i][pos];
                float av = std::abs(v);
                if (av < minAbs1) {
                    minAbs2 = minAbs1;
                    minAbs1 = av;
                    minIdx = pos;
                } else if (av < minAbs2) {
                    minAbs2 = av;
                }
                if (v < 0.0f) signProd ^= 1;
            }

            const float scale = static_cast<float>(LDPC_SCALE_FACTOR);
            for (int pos = 0; pos < deg; pos++) {
                float v = v2c[i][pos];
                int outSign = signProd ^ (v < 0.0f ? 1 : 0);
                float mag = (pos == minIdx) ? minAbs2 : minAbs1;
                c2v[i][pos] = (outSign ? -1.0f : 1.0f) * mag * scale;
            }
        }

        // ── Hard decision and convergence check ───────────────────────────
        std::vector<uint8_t> hardBits(LDPC_N);
        for (int j = 0; j < LDPC_N; j++) {
            float total = llr[j];
            for (int k = 0; k < (int)m_varToCheck[j].size(); k++)
                total += c2v[m_varToCheck[j][k]][posInCheck[j][k]];
            hardBits[j] = (total < 0.0f) ? 1 : 0;
        }

        // Check H * cw = 0 (mod 2)
        converged = true;
        for (int i = 0; i < LDPC_M; i++) {
            int par = 0;
            for (int j : m_checkToVar[i]) par ^= hardBits[j];
            if (par != 0) { converged = false; break; }
        }

        if (converged) {
            std::vector<uint8_t> msgBits(LDPC_K);
            for (int i = 0; i < LDPC_K; i++)
                msgBits[i] = hardBits[m_colPerm[i]];
            return DecodeResult{packBits(msgBits), true, iter + 1};
        }
    }

    // Did not converge — return best hard decision
    std::vector<uint8_t> msgBits(LDPC_K);
    for (int i = 0; i < LDPC_K; i++) {
        float total = llr[m_colPerm[i]];
        for (int k = 0; k < (int)m_varToCheck[m_colPerm[i]].size(); k++)
            total += c2v[m_varToCheck[m_colPerm[i]][k]]
                        [posInCheck[m_colPerm[i]][k]];
        msgBits[i] = (total < 0.0f) ? 1 : 0;
    }
    return DecodeResult{packBits(msgBits), false, LDPC_MAX_ITERATIONS};
}

FEC::DecodeMessageResult FEC::decodeMessage(const std::vector<float>& llr,
                                             int nBlocks,
                                             int origLen) const {
    std::vector<uint8_t> bytes;
    bytes.reserve(nBlocks * LDPC_BYTES_PER_BLOCK);
    bool allConverged    = true;
    int  totalIterations = 0;

    for (int b = 0; b < nBlocks; b++) {
        int start = b * LDPC_N;
        if (start + LDPC_N > (int)llr.size()) break;
        std::vector<float> blockLLR(llr.begin() + start,
                                     llr.begin() + start + LDPC_N);
        auto res = decodeBlock(blockLLR);
        bytes.insert(bytes.end(), res.bytes.begin(), res.bytes.end());
        if (!res.converged) allConverged = false;
        totalIterations += res.iterations;
    }

    if ((int)bytes.size() > origLen)
        bytes.resize(origLen);
    return {bytes, allConverged, totalIterations};
}

// ── LLR conversion ────────────────────────────────────────────────────────

std::vector<float> FEC::softToLLR(
    const std::vector<std::vector<float>>& softSymbols) const
{
    const float EPS = 1e-10f;
    int nSymbols = static_cast<int>(softSymbols.size());
    std::vector<float> llr(nSymbols * BITS_PER_SYMBOL);

    for (int s = 0; s < nSymbols; s++) {
        const auto& energies = softSymbols[s];

        for (int b = 0; b < BITS_PER_SYMBOL; b++) {
            float sum0 = EPS, sum1 = EPS;
            for (int t = 0; t < NUM_TONES; t++) {
                int bitVal = (t >> (BITS_PER_SYMBOL - 1 - b)) & 1;
                if (bitVal == 0)
                    sum0 += energies[t];
                else
                    sum1 += energies[t];
            }
            llr[s * BITS_PER_SYMBOL + b] =
                std::log(sum0) - std::log(sum1);
        }
    }
    return llr;
}

} // namespace HavenFSK
